apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
        tier: backend
    spec:
      containers:
      - name: story
        image: j0nnyz/kub-data-demo:2
        env:
          - name: STORY_FOLDER
            valueFrom:
              configMapKeyRef:
                name: data-store-env
                key: folder
          # - name: STORY_FOLDER
          #   value: 'story'
        volumeMounts:
          - name: story-volume
            mountPath: /app/story
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # emptyDir: {}