apiVersion: v1
kind: Service
metadata:
  name: story-service
  labels:
    group: example
spec:
  selector:
    app: story
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3001
  type: LoadBalancer
