apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: j0nnyz/kub-demo-users:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"    
    #       env:
    #         - name: TASKS_FOLDER
    #           value: tasks
    #         - name: AUTH_URL
    #           value: http://auth:8080
    #         - name: USERS_URL
    #           value: http://users:8080
    #         - name: TASKS_URL
    #           value: http://tasks:8008
