apiVersion: v1
kind: Service 
metadata:
  name: users-service
  # labels:
  #   app: users
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
      app: users